CREATE TABLE `ESPECIALIDAD`(
    `Id_especialidad` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `nombre` VARCHAR(255) NOT NULL
);
CREATE TABLE `CARRERA_TECNICA`(
    `Id_carrera` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `Nombre` VARCHAR(255) NOT NULL,
    `Titulo` VARCHAR(255) NOT NULL
);
CREATE TABLE `INSTRUCTOR`(
    `Id_instructor` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `Nombre` VARCHAR(255) NOT NULL,
    `Id_especialidad` INT NOT NULL
);
CREATE TABLE `RUTA_CURSO`(
    `Id_curso` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `Id_ruta` INT NOT NULL
);
CREATE TABLE `CURSOS`(
    `Id_curso` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `Name` VARCHAR(255) NOT NULL,
    `Id_instructor` INT NOT NULL
);
CREATE TABLE `RUTAS`(
    `Id_ruta` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `Nombre` VARCHAR(255) NOT NULL,
    `Id_carrera` INT NOT NULL
);
CREATE TABLE `APRENDICES`(
    `Id_aprendiz` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `Nombre` VARCHAR(255) NOT NULL,
    `Id_ruta` INT NOT NULL
);
ALTER TABLE
    `RUTAS` ADD CONSTRAINT `rutas_id_carrera_foreign` FOREIGN KEY(`Id_carrera`) REFERENCES `CARRERA_TECNICA`(`Id_carrera`);
ALTER TABLE
    `CURSOS` ADD CONSTRAINT `cursos_id_curso_foreign` FOREIGN KEY(`Id_curso`) REFERENCES `RUTA_CURSO`(`Id_curso`);
ALTER TABLE
    `INSTRUCTOR` ADD CONSTRAINT `instructor_id_especialidad_foreign` FOREIGN KEY(`Id_especialidad`) REFERENCES `ESPECIALIDAD`(`Id_especialidad`);
ALTER TABLE
    `RUTA_CURSO` ADD CONSTRAINT `ruta_curso_id_ruta_foreign` FOREIGN KEY(`Id_ruta`) REFERENCES `RUTAS`(`Id_ruta`);
ALTER TABLE
    `CURSOS` ADD CONSTRAINT `cursos_id_instructor_foreign` FOREIGN KEY(`Id_instructor`) REFERENCES `INSTRUCTOR`(`Id_instructor`);
ALTER TABLE
    `APRENDICES` ADD CONSTRAINT `aprendices_id_ruta_foreign` FOREIGN KEY(`Id_ruta`) REFERENCES `RUTAS`(`Id_ruta`);